### ISSUE TITLE
Also draw eyes for components?

### ISSUE THREAD

**Issue by LettError** [ryanbugden/Eyeliner#21]
Something to think about, not super necessary. If the glyph is first processed with a decomposing pen, all existing analysis and drawing that follows would also work for glyphs with components. Which may be useful when positioning things.

**Comment by ryanbugden** [comment]
@LettError Good idea! I wonder if that might make it more performant too.

The one thing I was hung up on for this was that components don't show points. Do you think I should try to fake them, and then add eyes? I guess could turn on and off with a pref.

**Comment by LettError** [comment]
Maybe only draw something for a point caught in an eyeliner?

**Comment by ryanbugden** [comment]
Good idea, will give this a shot!

**Comment by ryanbugden** [comment]
Done, thanks for the ideas @LettError !
